'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace MnbServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetCurrenciesRequestBody", [Namespace]:="http://www.mnb.hu/webservices/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetCurrenciesRequestBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetCurrenciesResponseBody", [Namespace]:="http://www.mnb.hu/webservices/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetCurrenciesResponseBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GetCurrenciesResultField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property GetCurrenciesResult() As String
            Get
                Return Me.GetCurrenciesResultField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GetCurrenciesResultField, value) <> true) Then
                    Me.GetCurrenciesResultField = value
                    Me.RaisePropertyChanged("GetCurrenciesResult")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetCurrencyUnitsRequestBody", [Namespace]:="http://www.mnb.hu/webservices/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetCurrencyUnitsRequestBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private currencyNamesField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property currencyNames() As String
            Get
                Return Me.currencyNamesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.currencyNamesField, value) <> true) Then
                    Me.currencyNamesField = value
                    Me.RaisePropertyChanged("currencyNames")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetCurrencyUnitsResponseBody", [Namespace]:="http://www.mnb.hu/webservices/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetCurrencyUnitsResponseBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GetCurrencyUnitsResultField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property GetCurrencyUnitsResult() As String
            Get
                Return Me.GetCurrencyUnitsResultField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GetCurrencyUnitsResultField, value) <> true) Then
                    Me.GetCurrencyUnitsResultField = value
                    Me.RaisePropertyChanged("GetCurrencyUnitsResult")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetCurrentExchangeRatesRequestBody", [Namespace]:="http://www.mnb.hu/webservices/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetCurrentExchangeRatesRequestBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetCurrentExchangeRatesResponseBody", [Namespace]:="http://www.mnb.hu/webservices/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetCurrentExchangeRatesResponseBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GetCurrentExchangeRatesResultField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property GetCurrentExchangeRatesResult() As String
            Get
                Return Me.GetCurrentExchangeRatesResultField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GetCurrentExchangeRatesResultField, value) <> true) Then
                    Me.GetCurrentExchangeRatesResultField = value
                    Me.RaisePropertyChanged("GetCurrentExchangeRatesResult")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetDateIntervalRequestBody", [Namespace]:="http://www.mnb.hu/webservices/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetDateIntervalRequestBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetDateIntervalResponseBody", [Namespace]:="http://www.mnb.hu/webservices/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetDateIntervalResponseBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GetDateIntervalResultField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property GetDateIntervalResult() As String
            Get
                Return Me.GetDateIntervalResultField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GetDateIntervalResultField, value) <> true) Then
                    Me.GetDateIntervalResultField = value
                    Me.RaisePropertyChanged("GetDateIntervalResult")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetExchangeRatesRequestBody", [Namespace]:="http://www.mnb.hu/webservices/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetExchangeRatesRequestBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private startDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private endDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private currencyNamesField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property startDate() As String
            Get
                Return Me.startDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.startDateField, value) <> true) Then
                    Me.startDateField = value
                    Me.RaisePropertyChanged("startDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property endDate() As String
            Get
                Return Me.endDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.endDateField, value) <> true) Then
                    Me.endDateField = value
                    Me.RaisePropertyChanged("endDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property currencyNames() As String
            Get
                Return Me.currencyNamesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.currencyNamesField, value) <> true) Then
                    Me.currencyNamesField = value
                    Me.RaisePropertyChanged("currencyNames")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetExchangeRatesResponseBody", [Namespace]:="http://www.mnb.hu/webservices/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetExchangeRatesResponseBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GetExchangeRatesResultField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property GetExchangeRatesResult() As String
            Get
                Return Me.GetExchangeRatesResultField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GetExchangeRatesResultField, value) <> true) Then
                    Me.GetExchangeRatesResultField = value
                    Me.RaisePropertyChanged("GetExchangeRatesResult")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetInfoRequestBody", [Namespace]:="http://www.mnb.hu/webservices/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetInfoRequestBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetInfoResponseBody", [Namespace]:="http://www.mnb.hu/webservices/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetInfoResponseBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GetInfoResultField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property GetInfoResult() As String
            Get
                Return Me.GetInfoResultField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GetInfoResultField, value) <> true) Then
                    Me.GetInfoResultField = value
                    Me.RaisePropertyChanged("GetInfoResult")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.mnb.hu/webservices/", ConfigurationName:="MnbServiceReference.MNBArfolyamServiceSoap")>  _
    Public Interface MNBArfolyamServiceSoap
        
        'CODEGEN: Generating message contract since the operation GetCurrencies is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", ReplyAction:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(String), Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesStringFault", Name:="string", [Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/")>  _
        Function GetCurrencies(ByVal request As MnbServiceReference.GetCurrenciesRequest) As MnbServiceReference.GetCurrenciesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", ReplyAction:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse")>  _
        Function GetCurrenciesAsync(ByVal request As MnbServiceReference.GetCurrenciesRequest) As System.Threading.Tasks.Task(Of MnbServiceReference.GetCurrenciesResponse)
        
        'CODEGEN: Generating message contract since the operation GetCurrencyUnits is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", ReplyAction:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(String), Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsStringFault", Name:="string", [Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/")>  _
        Function GetCurrencyUnits(ByVal request As MnbServiceReference.GetCurrencyUnitsRequest) As MnbServiceReference.GetCurrencyUnitsResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", ReplyAction:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse")>  _
        Function GetCurrencyUnitsAsync(ByVal request As MnbServiceReference.GetCurrencyUnitsRequest) As System.Threading.Tasks.Task(Of MnbServiceReference.GetCurrencyUnitsResponse)
        
        'CODEGEN: Generating message contract since the operation GetCurrentExchangeRates is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", ReplyAction:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesRespo"& _ 
            "nse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(String), Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesStrin"& _ 
            "gFault", Name:="string", [Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/")>  _
        Function GetCurrentExchangeRates(ByVal request As MnbServiceReference.GetCurrentExchangeRatesRequest) As MnbServiceReference.GetCurrentExchangeRatesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", ReplyAction:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesRespo"& _ 
            "nse")>  _
        Function GetCurrentExchangeRatesAsync(ByVal request As MnbServiceReference.GetCurrentExchangeRatesRequest) As System.Threading.Tasks.Task(Of MnbServiceReference.GetCurrentExchangeRatesResponse)
        
        'CODEGEN: Generating message contract since the operation GetDateInterval is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", ReplyAction:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(String), Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalStringFault", Name:="string", [Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/")>  _
        Function GetDateInterval(ByVal request As MnbServiceReference.GetDateIntervalRequest) As MnbServiceReference.GetDateIntervalResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", ReplyAction:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse")>  _
        Function GetDateIntervalAsync(ByVal request As MnbServiceReference.GetDateIntervalRequest) As System.Threading.Tasks.Task(Of MnbServiceReference.GetDateIntervalResponse)
        
        'CODEGEN: Generating message contract since the operation GetExchangeRates is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", ReplyAction:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(String), Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesStringFault", Name:="string", [Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/")>  _
        Function GetExchangeRates(ByVal request As MnbServiceReference.GetExchangeRatesRequest) As MnbServiceReference.GetExchangeRatesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", ReplyAction:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse")>  _
        Function GetExchangeRatesAsync(ByVal request As MnbServiceReference.GetExchangeRatesRequest) As System.Threading.Tasks.Task(Of MnbServiceReference.GetExchangeRatesResponse)
        
        'CODEGEN: Generating message contract since the operation GetInfo is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", ReplyAction:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(String), Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoStringFault", Name:="string", [Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/")>  _
        Function GetInfo(ByVal request As MnbServiceReference.GetInfoRequest) As MnbServiceReference.GetInfoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", ReplyAction:="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse")>  _
        Function GetInfoAsync(ByVal request As MnbServiceReference.GetInfoRequest) As System.Threading.Tasks.Task(Of MnbServiceReference.GetInfoResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetCurrenciesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.mnb.hu/webservices/", Order:=0)>  _
        Public GetCurrencies As MnbServiceReference.GetCurrenciesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetCurrencies As MnbServiceReference.GetCurrenciesRequestBody)
            MyBase.New
            Me.GetCurrencies = GetCurrencies
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetCurrenciesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetCurrenciesResponse", [Namespace]:="http://www.mnb.hu/webservices/", Order:=0)>  _
        Public GetCurrenciesResponse1 As MnbServiceReference.GetCurrenciesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetCurrenciesResponse1 As MnbServiceReference.GetCurrenciesResponseBody)
            MyBase.New
            Me.GetCurrenciesResponse1 = GetCurrenciesResponse1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetCurrencyUnitsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.mnb.hu/webservices/", Order:=0)>  _
        Public GetCurrencyUnits As MnbServiceReference.GetCurrencyUnitsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetCurrencyUnits As MnbServiceReference.GetCurrencyUnitsRequestBody)
            MyBase.New
            Me.GetCurrencyUnits = GetCurrencyUnits
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetCurrencyUnitsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetCurrencyUnitsResponse", [Namespace]:="http://www.mnb.hu/webservices/", Order:=0)>  _
        Public GetCurrencyUnitsResponse1 As MnbServiceReference.GetCurrencyUnitsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetCurrencyUnitsResponse1 As MnbServiceReference.GetCurrencyUnitsResponseBody)
            MyBase.New
            Me.GetCurrencyUnitsResponse1 = GetCurrencyUnitsResponse1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetCurrentExchangeRatesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.mnb.hu/webservices/", Order:=0)>  _
        Public GetCurrentExchangeRates As MnbServiceReference.GetCurrentExchangeRatesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetCurrentExchangeRates As MnbServiceReference.GetCurrentExchangeRatesRequestBody)
            MyBase.New
            Me.GetCurrentExchangeRates = GetCurrentExchangeRates
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetCurrentExchangeRatesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetCurrentExchangeRatesResponse", [Namespace]:="http://www.mnb.hu/webservices/", Order:=0)>  _
        Public GetCurrentExchangeRatesResponse1 As MnbServiceReference.GetCurrentExchangeRatesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetCurrentExchangeRatesResponse1 As MnbServiceReference.GetCurrentExchangeRatesResponseBody)
            MyBase.New
            Me.GetCurrentExchangeRatesResponse1 = GetCurrentExchangeRatesResponse1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDateIntervalRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.mnb.hu/webservices/", Order:=0)>  _
        Public GetDateInterval As MnbServiceReference.GetDateIntervalRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDateInterval As MnbServiceReference.GetDateIntervalRequestBody)
            MyBase.New
            Me.GetDateInterval = GetDateInterval
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDateIntervalResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDateIntervalResponse", [Namespace]:="http://www.mnb.hu/webservices/", Order:=0)>  _
        Public GetDateIntervalResponse1 As MnbServiceReference.GetDateIntervalResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDateIntervalResponse1 As MnbServiceReference.GetDateIntervalResponseBody)
            MyBase.New
            Me.GetDateIntervalResponse1 = GetDateIntervalResponse1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetExchangeRatesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.mnb.hu/webservices/", Order:=0)>  _
        Public GetExchangeRates As MnbServiceReference.GetExchangeRatesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetExchangeRates As MnbServiceReference.GetExchangeRatesRequestBody)
            MyBase.New
            Me.GetExchangeRates = GetExchangeRates
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetExchangeRatesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetExchangeRatesResponse", [Namespace]:="http://www.mnb.hu/webservices/", Order:=0)>  _
        Public GetExchangeRatesResponse1 As MnbServiceReference.GetExchangeRatesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetExchangeRatesResponse1 As MnbServiceReference.GetExchangeRatesResponseBody)
            MyBase.New
            Me.GetExchangeRatesResponse1 = GetExchangeRatesResponse1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetInfoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.mnb.hu/webservices/", Order:=0)>  _
        Public GetInfo As MnbServiceReference.GetInfoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetInfo As MnbServiceReference.GetInfoRequestBody)
            MyBase.New
            Me.GetInfo = GetInfo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetInfoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetInfoResponse", [Namespace]:="http://www.mnb.hu/webservices/", Order:=0)>  _
        Public GetInfoResponse1 As MnbServiceReference.GetInfoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetInfoResponse1 As MnbServiceReference.GetInfoResponseBody)
            MyBase.New
            Me.GetInfoResponse1 = GetInfoResponse1
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MNBArfolyamServiceSoapChannel
        Inherits MnbServiceReference.MNBArfolyamServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MNBArfolyamServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of MnbServiceReference.MNBArfolyamServiceSoap)
        Implements MnbServiceReference.MNBArfolyamServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MnbServiceReference_MNBArfolyamServiceSoap_GetCurrencies(ByVal request As MnbServiceReference.GetCurrenciesRequest) As MnbServiceReference.GetCurrenciesResponse Implements MnbServiceReference.MNBArfolyamServiceSoap.GetCurrencies
            Return MyBase.Channel.GetCurrencies(request)
        End Function
        
        Public Function GetCurrencies(ByVal GetCurrencies1 As MnbServiceReference.GetCurrenciesRequestBody) As MnbServiceReference.GetCurrenciesResponseBody
            Dim inValue As MnbServiceReference.GetCurrenciesRequest = New MnbServiceReference.GetCurrenciesRequest()
            inValue.GetCurrencies = GetCurrencies1
            Dim retVal As MnbServiceReference.GetCurrenciesResponse = CType(Me,MnbServiceReference.MNBArfolyamServiceSoap).GetCurrencies(inValue)
            Return retVal.GetCurrenciesResponse1
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MnbServiceReference_MNBArfolyamServiceSoap_GetCurrenciesAsync(ByVal request As MnbServiceReference.GetCurrenciesRequest) As System.Threading.Tasks.Task(Of MnbServiceReference.GetCurrenciesResponse) Implements MnbServiceReference.MNBArfolyamServiceSoap.GetCurrenciesAsync
            Return MyBase.Channel.GetCurrenciesAsync(request)
        End Function
        
        Public Function GetCurrenciesAsync(ByVal GetCurrencies As MnbServiceReference.GetCurrenciesRequestBody) As System.Threading.Tasks.Task(Of MnbServiceReference.GetCurrenciesResponse)
            Dim inValue As MnbServiceReference.GetCurrenciesRequest = New MnbServiceReference.GetCurrenciesRequest()
            inValue.GetCurrencies = GetCurrencies
            Return CType(Me,MnbServiceReference.MNBArfolyamServiceSoap).GetCurrenciesAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MnbServiceReference_MNBArfolyamServiceSoap_GetCurrencyUnits(ByVal request As MnbServiceReference.GetCurrencyUnitsRequest) As MnbServiceReference.GetCurrencyUnitsResponse Implements MnbServiceReference.MNBArfolyamServiceSoap.GetCurrencyUnits
            Return MyBase.Channel.GetCurrencyUnits(request)
        End Function
        
        Public Function GetCurrencyUnits(ByVal GetCurrencyUnits1 As MnbServiceReference.GetCurrencyUnitsRequestBody) As MnbServiceReference.GetCurrencyUnitsResponseBody
            Dim inValue As MnbServiceReference.GetCurrencyUnitsRequest = New MnbServiceReference.GetCurrencyUnitsRequest()
            inValue.GetCurrencyUnits = GetCurrencyUnits1
            Dim retVal As MnbServiceReference.GetCurrencyUnitsResponse = CType(Me,MnbServiceReference.MNBArfolyamServiceSoap).GetCurrencyUnits(inValue)
            Return retVal.GetCurrencyUnitsResponse1
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MnbServiceReference_MNBArfolyamServiceSoap_GetCurrencyUnitsAsync(ByVal request As MnbServiceReference.GetCurrencyUnitsRequest) As System.Threading.Tasks.Task(Of MnbServiceReference.GetCurrencyUnitsResponse) Implements MnbServiceReference.MNBArfolyamServiceSoap.GetCurrencyUnitsAsync
            Return MyBase.Channel.GetCurrencyUnitsAsync(request)
        End Function
        
        Public Function GetCurrencyUnitsAsync(ByVal GetCurrencyUnits As MnbServiceReference.GetCurrencyUnitsRequestBody) As System.Threading.Tasks.Task(Of MnbServiceReference.GetCurrencyUnitsResponse)
            Dim inValue As MnbServiceReference.GetCurrencyUnitsRequest = New MnbServiceReference.GetCurrencyUnitsRequest()
            inValue.GetCurrencyUnits = GetCurrencyUnits
            Return CType(Me,MnbServiceReference.MNBArfolyamServiceSoap).GetCurrencyUnitsAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MnbServiceReference_MNBArfolyamServiceSoap_GetCurrentExchangeRates(ByVal request As MnbServiceReference.GetCurrentExchangeRatesRequest) As MnbServiceReference.GetCurrentExchangeRatesResponse Implements MnbServiceReference.MNBArfolyamServiceSoap.GetCurrentExchangeRates
            Return MyBase.Channel.GetCurrentExchangeRates(request)
        End Function
        
        Public Function GetCurrentExchangeRates(ByVal GetCurrentExchangeRates1 As MnbServiceReference.GetCurrentExchangeRatesRequestBody) As MnbServiceReference.GetCurrentExchangeRatesResponseBody
            Dim inValue As MnbServiceReference.GetCurrentExchangeRatesRequest = New MnbServiceReference.GetCurrentExchangeRatesRequest()
            inValue.GetCurrentExchangeRates = GetCurrentExchangeRates1
            Dim retVal As MnbServiceReference.GetCurrentExchangeRatesResponse = CType(Me,MnbServiceReference.MNBArfolyamServiceSoap).GetCurrentExchangeRates(inValue)
            Return retVal.GetCurrentExchangeRatesResponse1
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MnbServiceReference_MNBArfolyamServiceSoap_GetCurrentExchangeRatesAsync(ByVal request As MnbServiceReference.GetCurrentExchangeRatesRequest) As System.Threading.Tasks.Task(Of MnbServiceReference.GetCurrentExchangeRatesResponse) Implements MnbServiceReference.MNBArfolyamServiceSoap.GetCurrentExchangeRatesAsync
            Return MyBase.Channel.GetCurrentExchangeRatesAsync(request)
        End Function
        
        Public Function GetCurrentExchangeRatesAsync(ByVal GetCurrentExchangeRates As MnbServiceReference.GetCurrentExchangeRatesRequestBody) As System.Threading.Tasks.Task(Of MnbServiceReference.GetCurrentExchangeRatesResponse)
            Dim inValue As MnbServiceReference.GetCurrentExchangeRatesRequest = New MnbServiceReference.GetCurrentExchangeRatesRequest()
            inValue.GetCurrentExchangeRates = GetCurrentExchangeRates
            Return CType(Me,MnbServiceReference.MNBArfolyamServiceSoap).GetCurrentExchangeRatesAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MnbServiceReference_MNBArfolyamServiceSoap_GetDateInterval(ByVal request As MnbServiceReference.GetDateIntervalRequest) As MnbServiceReference.GetDateIntervalResponse Implements MnbServiceReference.MNBArfolyamServiceSoap.GetDateInterval
            Return MyBase.Channel.GetDateInterval(request)
        End Function
        
        Public Function GetDateInterval(ByVal GetDateInterval1 As MnbServiceReference.GetDateIntervalRequestBody) As MnbServiceReference.GetDateIntervalResponseBody
            Dim inValue As MnbServiceReference.GetDateIntervalRequest = New MnbServiceReference.GetDateIntervalRequest()
            inValue.GetDateInterval = GetDateInterval1
            Dim retVal As MnbServiceReference.GetDateIntervalResponse = CType(Me,MnbServiceReference.MNBArfolyamServiceSoap).GetDateInterval(inValue)
            Return retVal.GetDateIntervalResponse1
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MnbServiceReference_MNBArfolyamServiceSoap_GetDateIntervalAsync(ByVal request As MnbServiceReference.GetDateIntervalRequest) As System.Threading.Tasks.Task(Of MnbServiceReference.GetDateIntervalResponse) Implements MnbServiceReference.MNBArfolyamServiceSoap.GetDateIntervalAsync
            Return MyBase.Channel.GetDateIntervalAsync(request)
        End Function
        
        Public Function GetDateIntervalAsync(ByVal GetDateInterval As MnbServiceReference.GetDateIntervalRequestBody) As System.Threading.Tasks.Task(Of MnbServiceReference.GetDateIntervalResponse)
            Dim inValue As MnbServiceReference.GetDateIntervalRequest = New MnbServiceReference.GetDateIntervalRequest()
            inValue.GetDateInterval = GetDateInterval
            Return CType(Me,MnbServiceReference.MNBArfolyamServiceSoap).GetDateIntervalAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MnbServiceReference_MNBArfolyamServiceSoap_GetExchangeRates(ByVal request As MnbServiceReference.GetExchangeRatesRequest) As MnbServiceReference.GetExchangeRatesResponse Implements MnbServiceReference.MNBArfolyamServiceSoap.GetExchangeRates
            Return MyBase.Channel.GetExchangeRates(request)
        End Function
        
        Public Function GetExchangeRates(ByVal GetExchangeRates1 As MnbServiceReference.GetExchangeRatesRequestBody) As MnbServiceReference.GetExchangeRatesResponseBody
            Dim inValue As MnbServiceReference.GetExchangeRatesRequest = New MnbServiceReference.GetExchangeRatesRequest()
            inValue.GetExchangeRates = GetExchangeRates1
            Dim retVal As MnbServiceReference.GetExchangeRatesResponse = CType(Me,MnbServiceReference.MNBArfolyamServiceSoap).GetExchangeRates(inValue)
            Return retVal.GetExchangeRatesResponse1
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MnbServiceReference_MNBArfolyamServiceSoap_GetExchangeRatesAsync(ByVal request As MnbServiceReference.GetExchangeRatesRequest) As System.Threading.Tasks.Task(Of MnbServiceReference.GetExchangeRatesResponse) Implements MnbServiceReference.MNBArfolyamServiceSoap.GetExchangeRatesAsync
            Return MyBase.Channel.GetExchangeRatesAsync(request)
        End Function
        
        Public Function GetExchangeRatesAsync(ByVal GetExchangeRates As MnbServiceReference.GetExchangeRatesRequestBody) As System.Threading.Tasks.Task(Of MnbServiceReference.GetExchangeRatesResponse)
            Dim inValue As MnbServiceReference.GetExchangeRatesRequest = New MnbServiceReference.GetExchangeRatesRequest()
            inValue.GetExchangeRates = GetExchangeRates
            Return CType(Me,MnbServiceReference.MNBArfolyamServiceSoap).GetExchangeRatesAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MnbServiceReference_MNBArfolyamServiceSoap_GetInfo(ByVal request As MnbServiceReference.GetInfoRequest) As MnbServiceReference.GetInfoResponse Implements MnbServiceReference.MNBArfolyamServiceSoap.GetInfo
            Return MyBase.Channel.GetInfo(request)
        End Function
        
        Public Function GetInfo(ByVal GetInfo1 As MnbServiceReference.GetInfoRequestBody) As MnbServiceReference.GetInfoResponseBody
            Dim inValue As MnbServiceReference.GetInfoRequest = New MnbServiceReference.GetInfoRequest()
            inValue.GetInfo = GetInfo1
            Dim retVal As MnbServiceReference.GetInfoResponse = CType(Me,MnbServiceReference.MNBArfolyamServiceSoap).GetInfo(inValue)
            Return retVal.GetInfoResponse1
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MnbServiceReference_MNBArfolyamServiceSoap_GetInfoAsync(ByVal request As MnbServiceReference.GetInfoRequest) As System.Threading.Tasks.Task(Of MnbServiceReference.GetInfoResponse) Implements MnbServiceReference.MNBArfolyamServiceSoap.GetInfoAsync
            Return MyBase.Channel.GetInfoAsync(request)
        End Function
        
        Public Function GetInfoAsync(ByVal GetInfo As MnbServiceReference.GetInfoRequestBody) As System.Threading.Tasks.Task(Of MnbServiceReference.GetInfoResponse)
            Dim inValue As MnbServiceReference.GetInfoRequest = New MnbServiceReference.GetInfoRequest()
            inValue.GetInfo = GetInfo
            Return CType(Me,MnbServiceReference.MNBArfolyamServiceSoap).GetInfoAsync(inValue)
        End Function
    End Class
End Namespace
